stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cloud-ffl:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: 1450
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./cloud-ffl-dc.yaml