apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ffl
  namespace: twitter-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ffl
  template:
    metadata:
      labels:
        app: cloud-ffl
    spec:
      containers:
      - name: cloud-ffl
        image: registry:5000/cloud-ffl
        imagePullPolicy: Always
        env:
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: CONSUMER_KEY
              name: bottimus-twitter-bot
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: CONSUMER_SECRET
              name: bottimus-twitter-bot
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: KEY
              name: bottimus-twitter-bot
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: SECRET
              name: bottimus-twitter-bot
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: cloud-redis
        - name: HOST
          valueFrom:
            secretKeyRef:
              key: HOST
              name: cloud-redis
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass
        - name: REDI_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass